### ISSUE TITLE
Authentication failed, Error 401

### ISSUE THREAD

**Issue by oczr** [anxdpanic/plugin.video.twitch#318]
Hey,

is it possible that they updated something?
Every time I try to start a VOD, I get the following error message:

[401] {"code"401,"status":"authentication failed"}

Worked without problems last night and I did not change anything.
Tried to reinstall the add-on and getting a new oauth token.
Did not help.

Sadly I can't provide any other details.

**Comment by Bananaburger** [comment]
I'm getting the same thing. I also tried changing my oauth token with no luck.

**Comment by ttrei** [comment]
I'm also affected.

**Comment by cpoppema** [comment]
Same thing here, I have generated a new token but that did not help.

What works for me is downgrading to 1.4.5. I am able to downgrade because I've had this package on the same device. I don't know how to downgrade if you only ever have had 2.0.0 on your device.
I did this by going to settings > add-ons > my add-ons > video add-ons > twitch: disable auto-update and open update > version 1.4.5 from local package cache.

The logfile does not really show anything more:

```
12:12:09 T:140093067077376   ERROR: Twitch: Error |Unauthorized| |[401] {"code":401,"status":"authentication failed"}|
12:12:09 T:140094564210752   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.twitch/?video_id=vXXXXXXX&mode=play]
```

**Comment by ttrei** [comment]
It looks like some twitch API queries started to fail if OAuth token is present in the query.

Fixed here:
https://github.com/ttrei/script.module.python.twitch/tree/bugfix/auth_error

Get the installable zip file by "Clone or download" -> "Download ZIP"

Edit: the fix has been merged
https://github.com/MrSprigster/script.module.python.twitch

**Comment by anxdpanic** [comment]
New versions posted:
https://github.com/MrSprigster/Twitch-on-Kodi/releases/tag/2.0.1

**Comment by rubemlrm** [comment]
looks that it's fixed on the last update. but you need to update manually since in kodi repo still appears the 2.0.0 version.

**Comment by oczr** [comment]
Thanks guys! Works without any problems.
Good job.

**Comment by rubemlrm** [comment]
In one case , when i tried access to collections of a given channel i got the "Authentication failed, Error 401" message, but besides that its working like a charm.

**Comment by anxdpanic** [comment]
Thanks, collections will be fixed in the next bump of script.module.python.twitch. 
https://github.com/MrSprigster/script.module.python.twitch/commit/27967796fa6f3b48aea4f7e57b5f151f63078a46
Just waiting to confirm any other breakage, before bumping the version.

**Comment by niel** [comment]
How long before this update makes it to the Kodi repo? 
I'm getting a long list of content I'll have to catch up on ;-)

**Comment by MrSprigster** [comment]
I'll look at submitting to the official repo at the weekend if @anxdpanic is happy that things are stable enough to bump the version.

**Comment by niel** [comment]
Thanks for the update.
I have to hope Twitch keeps VODs for more than a week ;-)

**Comment by anxdpanic** [comment]
@MrSprigster: Should be good to go for both, module will need to be accepted first again due to the pagination fix in 1.0.1.

**Comment by MrSprigster** [comment]
Submitted. 👍

**Comment by nDmitry** [comment]
I'm still experiencing this error with 2.0.2 version installed. As far as I understand, `script.module.python.twitch` should be updated to 1.0.2 version here: https://github.com/MrSprigster/Twitch-on-Kodi/blob/master/addon.xml#L5

https://github.com/MrSprigster/script.module.python.twitch/releases/tag/1.0.2

**Comment by anxdpanic** [comment]
v1.0.1 is not on the official repo, only 1.0.2 and that dependency version in the addon.xml is a minimum required, so on official 2.0.2 won't install without updating script.module.python.twitch to 1.0.1 or greater(will be 1.0.2). 

If you are still experiencing it, please post a debug log and/or a way to reproduce.

**Comment by nDmitry** [comment]
My bad, OAuth token was indeed invalid this time)

**Comment by niel** [comment]
I've started seeing this again today. I've updated my OAuth toke several times to no avail. 
BTW the OAuth token is a real PITA to enter via TV remote, and is necessary couple times a month at least. Is it possible to allow logging in via password directly?
