### ISSUE TITLE
Audio/video out of sync

### ISSUE THREAD

**Issue by flos06** [anxdpanic/plugin.video.twitch#566]
### Context

Please provide any relevant information about your setup

* Add-on Version: 2.5.7
* Kodi Version: 19
* Kodi GUI Language: english
* Operating System: OSMC on RPI 4
* Operating System Language:

------

### Expected Behavior

Please describe the behavior you are expecting.

If I play a stream it should play both audio and video in sync

------

### Current Behavior

What is the current behavior?

The audio starts earlier than the video causing audio and video to be out of sync. The desync is different every time because it takes a different amount of time to load the video each time. This happens on all video qualities.

------

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1.  Select stream
2. 
3. 

------

### Log

Please include a complete [debug log](https://kodi.wiki/view/Log_file).

Don't have access right now, if needed I'll provide one later, however I don't suspect the logs will show anything regarding this?

------

### Additional Information

Please provide any additional information that may be helpful.

------

**Comment by cmsimike** [comment]
Are you seeing the video play for a bit with the audio getting out of sync then the video suddenly jump and it syncs up for a bit, only to drift away again?
I am running into the exact same issue but I don't think the plugin has any real control over that. Likely the issue is the video-related changes introduced in Kodi 19.
https://osmc.tv/2021/02/kodi-v19-matrix-is-here-heres-what-you-need-to-know/ > "Regressions and improvements"

I hope I'm wrong but let's see.

**Comment by cmsimike** [comment]
@flos06

FYI i (randomly) tried what was mentioned here, https://github.com/anxdpanic/Twitch-on-Kodi/issues/554
>It seems to be working after turning off DRM Decode (Settings->Player->Allow using DRM PRIME decoder)

and the sync issues seem to go away (this is ~5 mins of testing, where as with this enabled i'd get sync issues right away). try it out.

**Comment by DimmKG** [comment]
It's not related to the addon. This issue occurs with all FHD videos (except HEVC encoded). The solution is to enable "Only allow acceleration for HEVC" in Player settings (Arch Linux ARM's Kodi has this option).

**Comment by cmsimike** [comment]
I think this solution works about as good as disabling DRM deocding (which then disables hardware decoding entirely it seems). But with this setup, fps doesn't come close to 60 unfortunately. probably won't be that close until we get hardware decoding back 100% on the raspi.

**Comment by Sim209** [comment]
Thank you, you solved my problem before i share it!
Same problem on rpi4 - LibreElec 10RC1 - Kodi 19.1, solved by disable DRM PRIME encoder

**Comment by cmsimike** [comment]
@Sim209 For what it's worth, I'm now using libreelec 10 beta and I did not need to make any changes for video to work. I will double check. *My understanding* (pls someone tell me if I'm wrong, still trying to wrap my head around the video changes) is that libreelec added back in the hardware video decoding functionality previously available in kodi <= 18 so if you're using the correct libreelec version, video should work without a problem.

**Comment by DimmKG** [comment]
It performs much better after kernel updates, but the video still gets out of sync when using UI.

**Comment by cmsimike** [comment]
Agreed, I've seen that too. I guess I don't care as much about that since, while watching videos, the playback seems fine to me.

**Comment by Sim209** [comment]
@cmsimike 
Maybe you're right,  I've got problem when i xas playing twitch streams with the add-on (and when the stream had was at 60fps).  When playing the same stream directly (With impulse (pay with an external player) and yaste (play on my mediacenter)), i didn't have lag and unsynchronisation between audio and video.  In the other hand, I had no problem playing 4K video.
So, perhaps it was not exactly the same problem, but disable DRM Prime solved the lag i had on 60fps video played with twitch addon.

**Comment by rjousse18** [comment]
have you configured your interface in 4k60? because I had this problem too and it was due to the fact that the twitch video was over 30fps and I had configured my interface to 30fps

**Comment by ilikenwf** [comment]
I run Arch on a 4th gen intel i5, and find that the VAAPI decoding desyncs audio for one reason or another.
